export enum ActionTypes {
    GET_USERS = 'GET_USERS',
    CLEAR_USERS = 'CLEAR_USERS',
    GET_USER = 'GET_USER',
    CLEAR_USER = 'CLEAR_USER',
    SET_USER_LOADING = 'SET_USER_LOADING',

    GET_SKILLS = 'GET_SKILLS',
    SET_SKILL_LOADING = 'SET_SKILL_LOADING',
    GET_SKILL_TOPIC = 'GET_SKILL_TOPIC',
    CLEAR_SKILL_TOPIC = 'CLEAR_SKILL_TOPIC',
}