export enum ActionTypes {
    GET_USERS = 'GET_USERS',
    CLEAR_USERS = 'CLEAR_USERS',
    GET_USER = 'GET_USER',
    CLEAR_USER = 'CLEAR_USER',
    SET_USER_LOADING = 'SET_USER_LOADING',

    GET_SKILL_MATRIXES = 'GET_SKILL_MATRIXES',
    SET_SKILL_MATRIX_LOADING = 'SET_SKILL_MATRIX_LOADING'
}